import { NgModule } from '@angular/core';
import {
  RemixIconModule,
  RiAddCircleLine,
  RiAddLine,
  RiArrowDownSLine,
  RiCamera3Line,
  RiClipboardLine,
  RiCloseLine,
  RiCodeLine,
  RiDeleteBin2Line,
  RiErrorWarningLine,
  RiFoldersLine,
  RiFullscreenExitLine,
  RiFullscreenLine,
  RiHashtag,
  RiMoreLine,
  RiPaletteLine,
  RiPencilLine,
  RiRestartLine,
  RiSave2Line,
  RiSearchLine,
  RiShareBoxLine,
  RiShareCircleLine,
  RiShutDownLine,
  RiStarFill,
  RiStarLine,
  RiTimeLine,
  RiUser3Line,
} from 'angular-remix-icon';

const icons = {
  RiFoldersLine,
  RiStarLine,
  RiAddCircleLine,
  RiSearchLine,
  RiDeleteBin2Line,
  RiShareCircleLine,
  RiClipboardLine,
  RiFullscreenLine,
  RiPaletteLine,
  RiCodeLine,
  RiFullscreenExitLine,
  RiSave2Line,
  RiAddLine,
  RiStarFill,
  RiPencilLine,
  RiCloseLine,
  RiCamera3Line,
  RiShutDownLine,
  RiTimeLine,
  RiMoreLine,
  RiErrorWarningLine,
  RiShareBoxLine,
  RiRestartLine,
  RiUser3Line,
  RiHashtag,
  RiArrowDownSLine,
};
@NgModule({
  declarations: [],
  imports: [RemixIconModule.configure(icons)],
  exports: [RemixIconModule],
})
export class IconModule {}
